aerogear/aerogear-android-sdk

README.md
docs/README.md
docs/using_the_android_sdk_bom.md

Adds a directory for the preliminary SDK docs and a topic on how to use the BOM

AGDROID-698 add initial docs

---

.editorconfig
.github/CODE_OF_CONDUCT.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
LICENSE
docs/README.md
docs/architecture.md
docs/creating_service_module.md

Include contribution guidelines and developer guide.
JIRA: https://issues.jboss.org/browse/AGDROID-680
- Add contribution guide referencing existing material in the aerogear website, add information around the preliminary structure of the SDK.
- Add editorconfig file based on https://github.com/aerogear/ide-config
- Add PR template.

[AGDROID-680] contribution guide

---

.circleci/config.yml
README.md

* [AGDROID-665](https://issues.jboss.org/browse/AGDROID-665)

Add circle-ci

---

core/src/main/java/org/aerogear/mobile/core/BootstrapException.java
core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/ServiceModule.java
core/src/main/java/org/aerogear/mobile/core/ServiceModuleRegistry.java
core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreJsonParser.java
core/src/main/java/org/aerogear/mobile/core/configuration/ServiceConfiguration.java
core/src/main/java/org/aerogear/mobile/core/http/HttpServiceModule.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreParserTest.java
core/src/test/java/org/aerogear/mobile/core/ServiceRegistryTest.java
keycloak-service-module/src/main/java/org/aerogear/mobile/keycloak_service_module/KeyCloakService.java

This implements the ServiceRegistry as described in the aerogear-android-sdk proposal.
This implements the service registry system.  The Unit tests remonstrate how to use it, and additional sample code can be found here : https://github.com/secondsun/WipDemo

Service registry

---

core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/ServiceModuleRegistry.java
core/src/main/java/org/aerogear/mobile/core/executor/AppExecutors.java
core/src/main/java/org/aerogear/mobile/core/http/HttpRequest.java
core/src/main/java/org/aerogear/mobile/core/http/HttpResponse.java
core/src/main/java/org/aerogear/mobile/core/http/HttpServiceConfiguration.java
core/src/main/java/org/aerogear/mobile/core/http/HttpServiceModule.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpRequest.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpResponse.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
core/src/test/java/org/aerogear/mobile/core/HttpServiceModuleTest.java
keycloak-service-module/build.gradle
keycloak-service-module/src/main/java/org/aerogear/mobile/keycloak_service_module/KeyCloakService.java

JIRA: https://issues.jboss.org/browse/AGDROID-701
This is a basic HTTP module that uses OK Http to connect to remote services.
example usage may be found in this project : https://github.com/secondsun/WipDemo
This PR depends on https://github.com/aerogear/aerogear-android-sdk/pull/16

Http module

---

.gitignore
core/build.gradle
core/src/debug/assets/undefined-mobile-services.json
core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/ServiceModule.java
core/src/main/java/org/aerogear/mobile/core/ServiceModuleRegistry.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreParserTest.java
core/src/test/java/org/aerogear/mobile/core/ServiceRegistryTest.java
core/src/test/java/org/aerogear/mobile/core/Util.java
keycloak-service-module/src/main/java/org/aerogear/mobile/keycloak_service_module/KeyCloakService.java

JIRA: https://issues.jboss.org/browse/AGDROID-771
See the description for the JIRA.
@aidenkeating Does this help?
To test this you can run the unit tests `gradlew testDebug` and create a sample application that connects to mobile services.  You may use https://github.com/secondsun/WipDemo as a reference

Agdroid 711 config params

---

auth/build.gradle
build.gradle
core/build.gradle
keycloak-service-module/build.gradle

* [AGDROID-714](https://issues.jboss.org/browse/AGDROID-714)

Move library dependencies to the BOM

---

core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/logging/Logger.java
core/src/main/java/org/aerogear/mobile/core/logging/LoggerAdapter.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreTest.java

* [AGDROID-727](https://issues.jboss.org/browse/AGDROID-727)

Add logger in the MobileCore

---

auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/AbstractAuthenticator.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImpl.java
auth/src/main/java/org/aerogear/mobile/auth/configuration/AuthServiceConfiguration.java
auth/src/main/java/org/aerogear/mobile/auth/configuration/KeycloakConfiguration.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/OIDCCredentials.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipal.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserRole.java
auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
auth/src/test/java/org/aerogear/mobile/auth/utils/UserIdentityParserTest.java
example/src/main/java/org/aerogear/mobile/example/ui/AuthDetailsFragment.java
example/src/main/java/org/aerogear/mobile/example/ui/AuthFragment.java
example/src/main/java/org/aerogear/mobile/example/ui/MainActivity.java
example/src/main/res/values/strings.xml

Implement the logout function in the example app. 
* Address some comments from PR #37 
* Update UserPrinciple interface to extends the Serializable interface to allow instances to be easily pass around between activities.
* Implement the logout function in the example app
* Update the user details view to show user roles
To test, run the example app. You should be able to login/logout and check current logged user details.

 ✨ fix for logout and some small improvement

---

core/src/debug/assets/dummy-mobile-services.json
core/src/debug/assets/mobile-services.json
core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreJsonParser.java
core/src/main/java/org/aerogear/mobile/core/configuration/ServiceConfiguration.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreTest.java
core/src/test/java/org/aerogear/mobile/core/configuration/MobileCoreParserTest.java
docs/contributing-guide.adoc
metrics/src/main/java/org/aerogear/mobile/metrics/MetricsService.java
metrics/src/test/java/org/aerogear/mobile/metrics/MetricsServiceTest.java

Adjust json parser to new format

---

auth/src/main/java/org/aerogear/mobile/auth/user/RoleType.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserRole.java

Resolves #43
Make serializable exceptions not occur on app suspension.
Make everything that needs to be serializable serializable.

Update objects to be serializable if needed

---

auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/auth/AuthStateManager.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/AbstractAuthenticator.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticateOptions.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImpl.java
auth/src/main/java/org/aerogear/mobile/auth/configuration/AuthServiceConfiguration.java
auth/src/main/java/org/aerogear/mobile/auth/configuration/KeycloakConfiguration.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/IntegrityCheckParametersImpl.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/OIDCCredentials.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserRole.java
auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
auth/src/test/java/org/aerogear/mobile/auth/AuthServiceTest.java
auth/src/test/java/org/aerogear/mobile/auth/impl/UserPrincipalImplTest.java
auth/src/test/java/org/aerogear/mobile/auth/utils/UserIdentityParserTest.java
auth/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
core/src/main/java/org/aerogear/mobile/core/utils/SanityCheck.java
core/src/test/java/org/aerogear/mobile/core/utils/SanityCheckTest.java

JIRA: https://issues.jboss.org/browse/AGDROID-753
Added a SanityCheck object.
Added sanity check calls

Added sanity check

---

docs/getting-started/getting-started.adoc

https://github.com/aerogear/aerogear-android-sdk/issues/46
JIRA: https://issues.jboss.org/browse/AGDROID-757
I've added some sections and clarifications to the Getting Started doc.
@wei-lee @david-martin  I've tagged you both as reviewers since I saw issues from both of you on this issue.

Updating getting started doc

---

docs/getting-started/metrics.adoc

Add docs for how to use the metrics service
JIRA: https://issues.jboss.org/browse/AGDROID-732, https://issues.jboss.org/browse/AGDROID-731

add basic metrics docs

---

example/build.gradle
example/src/main/java/org/aerogear/mobile/example/ui/MainActivity.java
example/src/main/java/org/aerogear/mobile/example/ui/SecurityServiceFragment.java
example/src/main/res/drawable/ic_backup.xml
example/src/main/res/drawable/ic_debug.xml
example/src/main/res/drawable/ic_developer_options.xml
example/src/main/res/drawable/ic_device_os.xml
example/src/main/res/drawable/ic_emulator.xml
example/src/main/res/drawable/ic_encrypt.xml
example/src/main/res/drawable/ic_hooking.xml
example/src/main/res/drawable/ic_lock_screen.xml
example/src/main/res/drawable/ic_phone_lock.xml
example/src/main/res/drawable/ic_root.xml
example/src/main/res/layout/fragment_security_service.xml
example/src/main/res/menu/activity_main_drawer.xml
example/src/main/res/values/colors.xml
example/src/main/res/values/strings.xml

https://issues.jboss.org/browse/AEROGEAR-2114
This PR will add a view to the example app to allow us to run checks and view results during the self-defense check development.

AEROGEAR-2114 - Security Service view added to example app

---

core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java

Related issues: 
* [AGDROID-760](https://issues.jboss.org/browse/AGDROID-760)
Metrics payload structure update based on https://github.com/aerogear/proposals/pull/27
**Before**
```json
{
"app": {
"appVersion": "1.0",
"appId": "org.aerogear.mobile.example",
"sdkVersion": "5.0.0-SNAPSHOT"
},
"device": {
"platformVersion": "27",
"platform": "android"
},
"timestamp": 1519160637059,
"clientId": "8c64e364-4370-4cef-acc9-e77c65ff9c3a"
}
```
**After**
```json
{
"clientId": "8c64e364-4370-4cef-acc9-e77c65ff9c3a",
"timestamp": 1519160848642,
"data": {
"app": {
"appVersion": "1.0",
"appId": "org.aerogear.mobile.example",
"sdkVersion": "5.0.0-SNAPSHOT"
},
"device": {
"platformVersion": "27",
"platform": "android"
}
}
}
```

Update metrics payload structure

---

core/src/main/java/org/aerogear/mobile/core/http/HttpRequest.java
core/src/main/java/org/aerogear/mobile/core/http/HttpResponse.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpRequest.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpResponse.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
core/src/main/java/org/aerogear/mobile/core/utils/ClientIdGenerator.java
core/src/main/java/org/aerogear/mobile/core/utils/SanityCheck.java

some code improvements, and best practicses

some fixes on http and utils package

---

auth/build.gradle
auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/auth/AuthStateManager.java
auth/src/main/java/org/aerogear/mobile/security/Check.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheck.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckExecutor.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckResult.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
auth/src/main/java/org/aerogear/mobile/security/impl/SecurityCheckExecutorImpl.java
auth/src/main/java/org/aerogear/mobile/security/impl/SecurityCheckResultImpl.java
auth/src/main/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetric.java
auth/src/test/java/org/aerogear/mobile/security/SecurityServiceTest.java
auth/src/test/java/org/aerogear/mobile/security/impl/SecurityCheckExecutorTest.java
auth/src/test/java/org/aerogear/mobile/security/impl/SecurityCheckResultTest.java
auth/src/test/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetricTest.java
auth/src/test/java/org/aerogear/mobile/security/utils/MockSecurityCheck.java
core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/ServiceModule.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreTest.java
example/src/main/java/org/aerogear/mobile/example/ui/SecurityServiceFragment.java

Need initial interfaces to start development on implementation.
JIRA: https://issues.jboss.org/browse/AEROGEAR-2174
Add initial interfaces and classes

AEROGEAR-2174 Initial interfaces and classes for SecurityService

---

auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/auth/Callback.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImpl.java
auth/src/main/java/org/aerogear/mobile/auth/configuration/AuthServiceConfiguration.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/JwksManager.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/OIDCCredentials.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java

compacter code (e.g. remove unneeded things, use lambda, change javadoc)
make code more compact

:lipstick: compact code, and misc fixes

---

auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
auth/src/test/java/org/aerogear/mobile/auth/user/UserPrincipalImplTest.java

The `toString(`) was buggy, not correctly printing the names, also the implemtation was doing String concatenation. it also lacked a unit test
fixed impl + test

Fixing broken toString() impl, and adding test

---

core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreJsonParser.java
core/src/main/java/org/aerogear/mobile/core/configuration/ServiceConfiguration.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
core/src/main/java/org/aerogear/mobile/core/metrics/impl/AppMetrics.java
core/src/main/java/org/aerogear/mobile/core/metrics/impl/DeviceMetrics.java
core/src/main/java/org/aerogear/mobile/core/metrics/publisher/LoggerMetricsPublisher.java
core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java

:lipstick:  a bit of code cosmetics

Core fixes

---

docs/getting-started/auth.adoc

Tiny update. Add semi colon to make code compile if copied to an IDE.

Add Semi-colon

---

auth/src/main/java/org/aerogear/mobile/auth/user/RoleType.java
auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
auth/src/main/java/org/aerogear/mobile/security/impl/SecurityCheckExecutorImpl.java
auth/src/main/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetric.java

:lipstick: some more code improvements

---

auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/DefaultAuthenticateOptions.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/oidc/OIDCAuthenticatorImpl.java
auth/src/test/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticateOptionsTest.java
auth/src/test/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImplTest.java
example/src/main/java/org/aerogear/mobile/example/ui/AuthFragment.java

there was no OIDC on that class

Renaming OICDAuthOptions to DefaultAuthOptions

---

core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
core/src/test/java/org/aerogear/mobile/core/metrics/MetricsServiceTest.java
docs/getting-started/getting-started.adoc
example/src/main/java/org/aerogear/mobile/example/ExampleApplication.java
example/src/main/java/org/aerogear/mobile/example/ui/BaseActivity.java

* [AGDROID-760](https://issues.jboss.org/browse/AGDROID-760)

Stop to send default metrics automatically

---

docs/getting-started/auth.adoc

Small update to the docs to prevent an Incompatible types error in Android Studio.

Update Check Authenticated Example

---

core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreTest.java

See: https://github.com/aerogear/aerogear-android-sdk/issues/91

Expose config

---

docs/getting-started/auth.adoc

Some class names were updated, but the docs weren't. Fixing.

Updated Outdated Docs

---

auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
auth/src/main/java/org/aerogear/mobile/security/checks/DeveloperModeCheck.java
auth/src/test/java/org/aerogear/mobile/security/checks/DeveloperModeCheckTest.java
example/src/main/java/org/aerogear/mobile/example/ui/SecurityServiceFragment.java

JIRA: https://issues.jboss.org/browse/AEROGEAR-1978
Add another check `DeveloperModeCheck` for the Security Service

AEROGEAR-1978 - Add a Check to Detect Developer Mode Enabled

---

auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/auth/AuthStateManager.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/oidc/OIDCAuthenticatorImpl.java
auth/src/main/java/org/aerogear/mobile/auth/configuration/AuthServiceConfiguration.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/JwksManager.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/OIDCCredentials.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
core/src/main/java/org/aerogear/mobile/core/metrics/MetricsPublisher.java
core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
core/src/main/java/org/aerogear/mobile/core/utils/SanityCheck.java

Our javadoc was ridden with warnings and errors.  Now it is not.
GH Issue : https://github.com/aerogear/aerogear-android-sdk/issues/97
There were many errors and warnings in our javadocs that were causing the installation of the code to fail.  This meant that people were commiting code that could not be packaged as a dependency.

JavaDoc Fixes

---

docs/getting-started/metrics-development.adoc
docs/getting-started/metrics.adoc

Adjust documentation to suggestion made by @david-martin in https://github.com/aerogear/aerogear-ios-sdk/pull/21

Split metrics to user and contributor guide

---

core/src/debug/assets/empty-mobile-services.json
core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreTest.java

Review test quality and coverage status of current projects and find improvements.
[No Jira at the moment]
This only affects `MobileCore`.
A bit of refactorization to `MobileCoreTest` class, to make it more extendable.
Also some new test cases to increase coverage 79% -> 90% .

Refactors tests and improves coverage

---

core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java

Adjust default network timeouts.
Issue logged by @TommyJ1994

Adjust default network timeouts

---

docs/getting-started/auth-self-defence-checks.adoc

JIRA: https://issues.jboss.org/browse/AEROGEAR-1979
API docs for the self defence check feature

AEROGEAR-1979 - Self Defence Check API Docs

---

auth/src/main/java/org/aerogear/mobile/security/AbstractSecurityCheckExecutor.java
auth/src/main/java/org/aerogear/mobile/security/AsyncSecurityCheckExecutor.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheck.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckExecutor.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckResult.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
auth/src/main/java/org/aerogear/mobile/security/SyncSecurityCheckExecutor.java
auth/src/main/java/org/aerogear/mobile/security/checks/DebuggerCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/DeveloperModeCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/ScreenLockCheck.java
auth/src/main/java/org/aerogear/mobile/security/impl/SecurityCheckResultImpl.java
auth/src/main/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetric.java
auth/src/test/java/org/aerogear/mobile/security/SecurityCheckExecutorTest.java

JIRA: https://issues.jboss.org/browse/AEROGEAR-1981
Review and update the JavaDocs and adding in `SanityCheck.nonNull()` from the Core SDK where appropriate.

AEROGEAR-1981 - API Documentation using Javadoc

---

auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
auth/src/main/java/org/aerogear/mobile/security/checks/EncryptionCheck.java
auth/src/test/java/org/aerogear/mobile/security/checks/EncryptionCheckTest.java
example/src/main/java/org/aerogear/mobile/example/ui/SecurityServiceFragment.java
example/src/main/res/layout/fragment_security_service.xml

JIRA: https://issues.jboss.org/browse/AEROGEAR-2209
We created a function that allows the end developer to check if the devices file system is encrypted

AEROGEAR-2209 Add Encryption Check

---

auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipal.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
docs/getting-started/auth.adoc

Fixing issues outlined in - https://github.com/aerogear/aerogear-android-sdk/issues/104
Expose tokens and create documentation on how to get them.

Expose Tokens, Add Docs

---

build.gradle
core/build.gradle
core/src/test/java/org/aerogear/mobile/core/http/OkHttpServiceModuleTest.java

Adds a test for the redirect handling in the http service.

add a test for http redirects

---

docs/getting-started/auth-self-defence-checks.adoc

The following checks where added after the docs where merged:
- ALLOW_BACKUP_ENABLED
- HAS_ENCRYPTION_ENABLED
The above checks where added to the docs, complete with links to relative external resources.

Added extra checks to docs

---

auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/security/AsyncSecurityCheckExecutor.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheck.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckResult.java
auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
auth/src/main/java/org/aerogear/mobile/security/SyncSecurityCheckExecutor.java
auth/src/main/java/org/aerogear/mobile/security/checks/AllowBackupFlagCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/DebuggerCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/DeveloperModeCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/EmulatorCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/EncryptionCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
auth/src/main/java/org/aerogear/mobile/security/checks/ScreenLockCheck.java
auth/src/main/java/org/aerogear/mobile/security/impl/SecurityCheckResultImpl.java
auth/src/main/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetric.java
auth/src/test/java/org/aerogear/mobile/security/SecurityCheckExecutorTest.java
auth/src/test/java/org/aerogear/mobile/security/checks/DeveloperModeCheckTest.java
auth/src/test/java/org/aerogear/mobile/security/impl/SecurityCheckResultTest.java
auth/src/test/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetricTest.java
core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java
example/src/main/assets/mobile-services.json
example/src/main/java/org/aerogear/mobile/example/ui/SecurityServiceFragment.java

https://issues.jboss.org/browse/AEROGEAR-2218
https://issues.jboss.org/browse/AEROGEAR-2266
Readd the type and name fields to metrics data.

Fixes from e2e tests

---

core/src/main/java/org/aerogear/mobile/core/logging/Logger.java
core/src/main/java/org/aerogear/mobile/core/logging/LoggerAdapter.java
core/src/test/java/org/aerogear/mobile/core/MobileCoreTest.java

Related issues: 
* [AGDROID-795](https://issues.jboss.org/browse/AGDROID-795) - Change Logger to use Throwable instead of Exception

Update logger to use Throwable instead of Exception

---

README.md

Remove Duplicate Contributing Section

---

.github/PULL_REQUEST_TEMPLATE.md
Jenkinsfile
README.md

JIRA: https://issues.jboss.org/browse/AEROGEAR-2237
* added deploying of [app metrics (metrics api)](https://github.com/aerogear/aerogear-app-metrics) as a prerequisite of metrics integration test
* TBD: load url of metrics api and run metrics integration test (@josemigallas)
* this test will be triggered if PR is containing label "test/integration"

Metrics integration test

---

docs/getting-started/certificate-pinning.adoc
docs/getting-started/getting-started.adoc

JIRA: https://issues.jboss.org/browse/AEROGEAR-2224
Creating this PR to get these changes [#168](https://github.com/aerogear/aerogear-android-sdk/pull/168) merged.

AEROGEAR-2224 Certificate Pinning Information

---

auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/DefaultAuthenticateOptions.java
auth/src/main/java/org/aerogear/mobile/auth/authenticator/oidc/OIDCAuthenticatorImpl.java
core/src/main/java/org/aerogear/mobile/core/MobileCore.java
core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreConfiguration.java
core/src/main/java/org/aerogear/mobile/core/configuration/https/CertificatePinningEntry.java
core/src/main/java/org/aerogear/mobile/core/configuration/https/HttpsConfiguration.java
core/src/main/java/org/aerogear/mobile/core/http/OkHttpCertificatePinningParser.java
core/src/main/java/org/aerogear/mobile/core/http/pinning/CertificatePinningCheck.java

Changes where requested after PR [#175](https://github.com/aerogear/aerogear-android-sdk/pull/175) was merged
This PR addresses changes requested in a previous PR

Changes to Certificate Pinner

---

README.md

GitHub issue - https://github.com/aerogear/aerogear-android-sdk/issues/162
At the moment we do not supply any link to our self defence docs or our certificate pinning docs.

Links added to README.md

---

docs/getting-started/certificate-pinning.adoc

Update the `mobile-cli` flag due to changes made https://github.com/aerogear/mobile-cli/pull/71

Update Cert Pinning Doc

---

auth/src/main/java/org/aerogear/mobile/auth/authenticator/AuthorizationServiceFactory.java
auth/src/main/java/org/aerogear/mobile/auth/configuration/KeycloakConfiguration.java
auth/src/main/java/org/aerogear/mobile/auth/credentials/OIDCCredentials.java
auth/src/main/java/org/aerogear/mobile/auth/user/RoleType.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipal.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserRole.java
auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
auth/src/test/java/org/aerogear/mobile/auth/credentials/OIDCCredentialsTest.java
auth/src/test/java/org/aerogear/mobile/auth/user/UserPrincipalImplTest.java
auth/src/test/java/org/aerogear/mobile/auth/utils/UserIdentityParserTest.java
docs/getting-started/auth.adoc

Issue #138 
Rename client to resource for keycloak roles

Rename Client to Resource for Roles

---

auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
auth/src/test/java/org/aerogear/mobile/auth/AuthStateManagerTest.java
auth/src/test/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImplTest.java
auth/src/test/java/org/aerogear/mobile/auth/credentials/OIDCCredentialsTest.java
auth/src/test/java/org/aerogear/mobile/auth/utils/UserIdentityParserTest.java

Issue #98 
Refactored throws `JSONException` to `try/catch` where functions are not parsing JSON & remove unused `JSONException` from functions

Remove unused and uneccessary JSONExceptions

---

push/src/main/java/org/aerogear/mobile/push/PushService.java
push/src/main/java/org/aerogear/mobile/push/fcm/AeroGearFirebaseInstanceIdService.java

Firebase changes the Device token from time to time and we need to update that on the UPS
See: https://firebase.google.com/docs/cloud-messaging/android/client#monitor-token-generation

Add push refresh token

---

auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipal.java
auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
auth/src/test/java/org/aerogear/mobile/auth/user/UserPrincipalImplTest.java
auth/src/test/java/org/aerogear/mobile/auth/utils/UserIdentityParserTest.java
docs/modules/getting-started/pages/auth.adoc

Github Issue #103 
Added `getRealmRoles()` and `getResourceRoles()` methods to improve the user experience of getting different users roles.

add getRealmRoles and getResourceRoles methods

---

core/src/main/java/org/aerogear/mobile/core/bootstrap/AeroGearBootstrap.java
example/src/main/java/org/aerogear/mobile/example/ExampleApplication.java

* [AGDROID-802](https://issues.jboss.org/browse/AGDROID-802)

Sending metrics automatically on init

---

core/src/main/java/org/aerogear/mobile/core/metrics/impl/AppMetrics.java

Add framework flag to Android SDK

AEROGEAR-2699: Add native framework flag

---

docs/modules/getting-started/pages/auth-self-defence-checks.adoc

https://github.com/aerogear/aerogear-js-sdk/pull/88
Based on feedback on the above PR I have made changes to update the current security check docs.

Update Security Docs

---

core/src/test/assets/mobile-services-multiple-services-for-type.json
core/src/test/assets/mobile-services.json

Currently integration tests are failing with an SSL Handshake error.

Fix failing integration test

---

docs/modules/ROOT/pages/index.adoc

Changes made based on feedback from the following PR https://github.com/aerogear/android-showcase-template/pull/11
Remove version numbers from docs
Remove core import from docs

Update getting started guide

---

README.md

@wtrocki thanks for spotting, time for a quick review so I can get this merged.

remove hash
