aerogear/aerogear-android-sdk

- build.gradle
Adds the spring dep management plugin and the new BOM from aerogear-parent.
Pending finishing publication of https://github.com/aerogear/aerogear-parent/releases/tag/1.1.7, with changes from https://github.com/aerogear/aerogear-parent/pull/75
> AGDROID-697 aerogear-parent BOM usage

- core/build.gradle
- core/src/debug/assets/mobile-core.json
- core/src/debug/assets/mobile-services.json
- core/src/main/java/org/aerogear/mobile/core/BootstrapException.java
- core/src/main/java/org/aerogear/mobile/core/MobileCore.java
- core/src/main/java/org/aerogear/mobile/core/ServiceModule.java
- core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreJsonParser.java
- core/src/main/java/org/aerogear/mobile/core/configuration/ServiceConfiguration.java
- core/src/test/AndroidManifest.xml
- core/src/test/java/org/aerogear/mobile/core/MobileCoreParserTest.java
- keycloak-service-module/src/main/java/org/aerogear/mobile/keycloak_service_module/KeyCloakService.java
This add support for parsing a mobile-core.json file from the mobile cli tool.
run `./gradlew testDebug` from the project root.  You should see in your gradle logs that the parsing tests for the example mobile-core.json file are run.
#Notes
This depends on PRs #4 and #5   Should we make changes to those we will need to rebase this PR.
> Agdroid 693 parse mobile core

- auth/src/main/java/org/aerogear/auth/IUserPrincipal.java
- auth/src/main/java/org/aerogear/auth/credentials/ICredential.java
- auth/src/main/java/org/aerogear/auth/credentials/OIDCCredentials.java
- auth/src/main/java/org/aerogear/auth/impl/OIDCUserPrincipalImpl.java
- auth/src/main/java/org/aerogear/auth/impl/UserPrincipalImpl.java
Allow checking for current auth status. Both is authorized and token isn't expired.
JIRA: https://issues.jboss.org/browse/AGDROID-682
Wraps AuthState some more with OIDCCredentials, mainly wrapping `isAuthorized()` and `getNeedsTokenRefresh()`.
Check these to determine the current auth state using `checkAuthState()`.
> AGDROID-682 Include checkAuthStatus

- core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreJsonParser.java
This should fix some problems with parsing mobile-services.json. Or was the fallthrough intended for some reason?
Tested with the following mobile-services.json file:
```
{
"services": [
{
"config": {
"headers": {
"User-Agent": "AeroGear Android Core"
},
"url": "http://http-myproject.192.168.37.1.nip.io"
},
"name": "http"
},
{
"config": {
"uri": "https://www.mocky.io/v2/5185415ba171ea3a00704eed"
},
"name": "metrics"
}
],
"namespace": "myproject"
}
```
> fix parsing for mobile config

- auth/src/main/java/org/aerogear/android/ags/auth/impl/OIDCAuthCodeImpl.java
- auth/src/main/java/org/aerogear/android/ags/auth/utils/UserIdentityParser.java
- auth/src/test/java/org/aerogear/android/ags/auth/utils/UserIdentityParserTest.java
The `OIDCAuthCodeImpl` class was looking a bit bloated with all that parsing functionality. 
Refactored that code out to its own separate utility class. These functions can be reused and tested easier.
> [Refactor] - decouple user identity parsing functionality into separate utility class

- auth/src/main/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImpl.java
Make logout work properly
Need to include the OpenID scope to get the identity token.
Login
Logout - Session will be removed on Keycloak
Login again - Will have to authenticate again
Resolves https://github.com/aerogear/aerogear-android-sdk/issues/42
> Update login request to include OpenID scope

- auth/build.gradle
- auth/gradle.properties
- auth/src/main/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImpl.java
- settings.gradle
At the moment, `./gradlew install` doesn't build the auth module.
Update the build configuration of the auth module to make it buildable
To test, run `./gradlew install`. It should finish successfully and the directory `~/.m2/repository/org/aerogear/auth` should exist.
ping @TommyJ1994
>  🚀  allow build the auth module

- core/src/main/java/org/aerogear/mobile/core/MobileCore.java
Some services need access to the Context to avoid explicit init it.
> Allow access to the application context from the MobileCore

- core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
- core/src/main/java/org/aerogear/mobile/core/metrics/metrics/DeviceMetrics.java
- core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java
- core/src/main/java/org/aerogear/mobile/core/utils/AppIdGenerator.java
- core/src/main/java/org/aerogear/mobile/core/utils/ClientIdGenerator.java
- core/src/test/java/org/aerogear/mobile/core/metrics/metrics/DeviceMetricsTest.java
Allow to have app id on the top level so we will be able to retrieve metrics for specific application (if needed)
Add timestamp as in proposal to track when metrics were collected and send 
WIP idea for additional requirements.
Two ways of doing this:
1. Change way we store metrics from `Metrics[]` to separate class containing it as field. 
1. Include that in publisher (probably worse) - implemented in this PR
> Flag required fields

- docs/getting-started/auth.adoc
By default, federated won't work unless the user enables backchannel logouts for their federated IDP.
Add a note for a how a user should enable this, otherwise there mobile app will experience unexpected behavior when trying to logout.
> Add Backchannel Logout Note

- docs/getting-started/auth.adoc
The current docs for Keycloak are available at [http://www.keycloak.org/docs/latest/](http://www.keycloak.org/docs/latest/). Updating some links to refer to the latest docs, as older docs for some versions have been removed in the past and result in 404's.
Update links.
> Use Keycloak Latest for Docs

- core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
- core/src/main/java/org/aerogear/mobile/core/metrics/impl/AppMetrics.java
- core/src/main/java/org/aerogear/mobile/core/metrics/impl/DeviceMetrics.java
- core/src/test/java/org/aerogear/mobile/core/metrics/impl/AppMetricsTest.java
- core/src/test/java/org/aerogear/mobile/core/metrics/impl/DeviceMetricsTest.java
package `metrics.metrics` looks more than just bizarre. Moving the two concrete 'implementations' for our Metrics to a slightly better named package (`impl`)
Fixing odd package structure
> Avoid double metrics.metrics package name

- README.md
Some links on the main README are 404'ing.
Update links to the getting started guide for Core and Auth.
> Add link to Core/Auth Getting Started Docs

- auth/src/test/java/org/aerogear/mobile/auth/AuthServiceTest.java
- auth/src/test/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticateOptionsTest.java
- auth/src/test/java/org/aerogear/mobile/auth/utils/UserIdentityParserTest.java
- core/src/main/java/org/aerogear/mobile/core/utils/SanityCheck.java
- core/src/test/java/org/aerogear/mobile/core/utils/SanityCheckTest.java
If a null object is passed in, as an _argument_, and `IllegalArgumentException` needs to be thrown. NPE is only good when you invoke a null objects. But for checks on passed in objects, it's `IllegalArgumentException`
see: https://stackoverflow.com/questions/3881/illegalargumentexception-or-nullpointerexception-for-a-null-parameter
> non null for passed in arguments should throw IllegalArgumentException

- auth/src/main/java/org/aerogear/mobile/auth/credentials/OIDCCredentials.java
- auth/src/test/java/org/aerogear/mobile/auth/credentials/OIDCCredentialsTest.java
throwing `UnsupportedOperationException` in `renew` and adding a test
> Some fixes on OIDCCredential clazz

- auth/src/main/java/org/aerogear/mobile/security/AbstractSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/AsyncSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheck.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
- auth/src/main/java/org/aerogear/mobile/security/SyncSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
- auth/src/test/java/org/aerogear/mobile/security/SecurityCheckExecutorTest.java
- auth/src/test/java/org/aerogear/mobile/security/utils/MockSecurityCheck.java
Added back the 'addCheck' method that was erroneously removed
Changed the return value of the check executors: now a Map is returned (key: check name, value check result).
Re-added the addCheckMethods
> Added back the 'addCheck' methods/Changed return value from array to Map

- auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
The example app was crashing when the self defense checks where loaded.
The crash was caused by a cast in the SecurityService class. We where trying to cast SecurityCheckResult to a SecurityCheck, by removing the cast and returning a SecurityCheckResult we stop the example app from crashing
> Example app crashing fix.

- auth/src/main/java/org/aerogear/mobile/security/checks/AbstractSecurityCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/DebuggerCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/DeveloperModeCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/EmulatorCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/ScreenLockCheck.java
Each security check marks the `context` as nonnull and sanity checks are duplicated in every security check implementation.
Moreover, each security check implementation is polluted with code to build the `SecurityCheckResult` object just to return a boolean.
Created a base class that delegates to subclasses the implementation of the check by simply implementing the `execute` method and just returning a `boolean`.
The `execute` method is guaranteed to receive a nonnull context, so no check need to be performed there.
The `SecurityResult` object is built in the base class automatically, so no need to worry about that in the real check implementation
> Added base class to remove duplicate code

- .circleci/config.yml
- auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
- auth/src/main/java/org/aerogear/mobile/security/checks/AbstractSecurityCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
- gradle-mvn-push.gradle
CircleCi didn't fail if there were javadoc warnings.  This was causing issues because some versions of javadoc are more strict and treat warnings as errors.
JIRA: https://issues.jboss.org/browse/AGDROID-768
You can follow my tests here : https://circleci.com/gh/secondsun/aerogear-android-sdk/tree/circleci_generate_maven_artifacts
One of things you might want to exercise when you test is adding javadoc errors locally and making sure that `./gradlew install` fails your build.  Bonus points if you test your own circleCi
> Circleci generate maven artifacts and test javadocs

- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
- auth/src/main/java/org/aerogear/mobile/security/checks/AllowBackupFlagCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/DebuggerCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/DeveloperModeCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/EmulatorCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/RootedCheck.java
- auth/src/main/java/org/aerogear/mobile/security/checks/ScreenLockCheck.java
- auth/src/test/java/org/aerogear/mobile/security/checks/AllowBackupFlagCheckTest.java
- example/src/main/java/org/aerogear/mobile/example/ui/SecurityServiceFragment.java
Add a check for `allowBackup` flag.
JIRA: https://issues.jboss.org/browse/AEROGEAR-2208
Checks whether the `allowBackup` flag is enabled.
Also, addressing errors from linting.
> AEROGEAR-2208 Add allow backup flag check

- core/src/main/java/org/aerogear/mobile/core/http/HttpResponse.java
- core/src/main/java/org/aerogear/mobile/core/http/InvalidResponseException.java
- core/src/main/java/org/aerogear/mobile/core/http/OkHttpResponse.java
- core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java
- core/src/test/java/org/aerogear/mobile/core/MobileCoreTest.java
- core/src/test/java/org/aerogear/mobile/core/http/OkHttpServiceModuleTest.java
Allow better error handling when using the http module and fix a bug in the metrics module. When the return code from a request was 500 the `onComplete` handler was triggered. The metrics module tried to evaluate the `requestError` but it was null. The current implementation does set the `requestError` only when the request itself failed, not when the response returned an invalid status code.
Example:
```java
final HttpResponse resp = httpRequest.execute();
resp.onSuccess(() -> {
// Do something with the result           
}).onError(() -> {
// Print an error message, you can safely access resp.getRequestError()
}).onComplete() -> {
// Close any resources, popups... This will always be called
});
```
Adds `onError` and `onSuccess` handlers to the `HttpResponse` objects. I've looked at the …
> implement http error handling

- auth/build.gradle
- auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
- auth/src/main/java/org/aerogear/mobile/auth/configuration/KeycloakConfiguration.java
- auth/src/main/java/org/aerogear/mobile/auth/credentials/OIDCCredentials.java
- auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipal.java
- auth/src/main/java/org/aerogear/mobile/security/AbstractSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/AsyncSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckExecutorListener.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckMetricPublisher.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckType.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
- auth/src/main/java/org/aerogear/mobile/security/SyncSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetric.java
- auth/src/test/java/org/aerogear/mobile/security/SecurityCheckExecutorTest.java
- auth/src/test/java/org/aerogear/mobile/security/metrics/SecurityCheckResultMetricTest.java
- core/src/main/java/org/aerogear/mobile/core/executor/AppExecutors.java
- core/src/main/java/org/aerogear/mobile/core/metrics/Metrics.java
- core/src/main/java/org/aerogear/mobile/core/metrics/impl/AppMetrics.java
- core/src/main/java/org/aerogear/mobile/core/metrics/impl/DeviceMetrics.java
- core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java
- core/src/test/java/org/aerogear/mobile/core/metrics/MetricsServiceTest.java
- core/src/test/java/org/aerogear/mobile/core/metrics/impl/AppMetricsTest.java
- core/src/test/java/org/aerogear/mobile/core/metrics/impl/DeviceMetricsTest.java
JIRA: https://issues.jboss.org/browse/AGDROID-771
Make both Sync and Async executors send a single metrics request upon finishing execution.
Update data being sent to match the server-side implementation at https://github.com/aerogear/aerogear-app-metrics/pull/33
> [AGDROID-771] Batch security metrics and update json schema

- auth/src/main/java/org/aerogear/mobile/security/AbstractSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/AsyncSecurityCheckExecutor.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckExecutorListener.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckMetricPublisher.java
- auth/src/main/java/org/aerogear/mobile/security/SyncSecurityCheckExecutor.java
Added event listener
Implementation proposal for batch metric publishing that avoids polluting the code with logic to batch the metrics.
We currently want to avoid modifying the metric service to add batch received metrics, so we have to add some batching logic to the async/sync security check executors.
This implementation adds the ability to pass `listeners` to the execute method, so that events can be received as the checks are executed (`onExecuted` and `onFinished`).
A `SecurityCheckMetricPublisher` class implementing the listener interface is provided to batch the metrics and publish them when `onFinished` is received.
With this approach we have two benefits:
1. The code to batch the metrics is outside the executor class
2. We provide the user another useful interface
We could …
> Added metric publishing batching

- auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
- auth/src/main/java/org/aerogear/mobile/auth/Callback.java
- auth/src/main/java/org/aerogear/mobile/auth/authenticator/AbstractAuthenticator.java
- auth/src/main/java/org/aerogear/mobile/auth/authenticator/oidc/OIDCAuthenticatorImpl.java
- auth/src/test/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImplTest.java
- docs/getting-started/auth.adoc
- example/src/main/java/org/aerogear/mobile/example/ui/AuthDetailsFragment.java
Detail in https://github.com/aerogear/aerogear-android-sdk/issues/96
Improves usage experience for - https://github.com/feedhenry/mobile-security-android-template/pull/36
Adding a callback for the logout function so it lets the user know if the logout has succeeded or not. 
Updated the Callback interface so that onSuccess can be called without the requirement to pass some data.
> Improve Logout Functionality

- auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipal.java
- auth/src/main/java/org/aerogear/mobile/auth/user/UserPrincipalImpl.java
- auth/src/main/java/org/aerogear/mobile/auth/utils/UserIdentityParser.java
- auth/src/test/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImplTest.java
- docs/getting-started/auth.adoc
We only currently expose the users username. This is not the same as a full name, it's a unique identifier that could be anything. We should also expose the first and last name of the user.
Updating the user principal to allow for a first name and a last name to be provided to it and retrieved from it. Update the example app to use `getUsername` instead of `getName`.
Resolves https://github.com/aerogear/aerogear-android-sdk/issues/89
> Give users first and last names

- example/src/main/assets/mobile-services.json
Previous metrics PR broke default  mobile-services.json. It was breaking my E2E tests.
> fixed mobile-services.json (it was broken)

- docs/getting-started/metrics.adoc
Remove contributor guide link from metrics user guide doc.
Same done on IOS: https://github.com/aerogear/aerogear-ios-sdk/pull/40
> Remove link to metrics contributor guide

- docs/getting-started/auth.adoc
- docs/getting-started/getting-started.adoc
Currently we do not link the video providing an end to end example
of using Keycloak in our documentation. This change adds the video
in the form of an image that once clicked will open YouTube.
The reason for not using the asciidoc video tag is because it does
not create the desired effect when rendered on GitHub.
This seems to be the best way to go about it if we want some visual
thing instead of just a link.
Add an image that links to the YouTube video.
> Add getting started video to auth SDK

- auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
Bug fix for issue https://github.com/aerogear/aerogear-android-sdk/issues/131 
JIRA: N/A
Error thrown when the token verification functions are being called when unauthenticated.
Verification:
Run the example app and select the auth option when not authenticated
Expected result:
No NullPointerException error relating to the token verification
> fix token verification bug - issue #131

- auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
- auth/src/main/java/org/aerogear/mobile/auth/authenticator/AbstractAuthenticator.java
- auth/src/main/java/org/aerogear/mobile/auth/authenticator/oidc/OIDCAuthenticatorImpl.java
- auth/src/main/java/org/aerogear/mobile/auth/credentials/JwksManager.java
- auth/src/test/java/org/aerogear/mobile/auth/authenticator/OIDCAuthenticatorImplTest.java
- auth/src/test/java/org/aerogear/mobile/auth/credentials/JwksManagerTest.java
- core/src/main/java/org/aerogear/mobile/core/Callback.java
- example/src/main/java/org/aerogear/mobile/example/ui/AuthDetailsFragment.java
- example/src/main/java/org/aerogear/mobile/example/ui/AuthFragment.java
There is a Callback class in the Auth module and it should be reused (for now) in the other modules, so it should be in Core instead of in Auth module.
> Move auth Callback to the core module

- docs/getting-started/auth-single-sign-on.adoc
The Direct Access Grant should not be enabled. SSO uses the Standard/Auth Code flow.
> Removed Unnecessary Direct Access Grant Step

- auth/src/main/java/org/aerogear/mobile/auth/authenticator/AuthorizationServiceFactory.java
- auth/src/main/java/org/aerogear/mobile/auth/configuration/AuthServiceConfiguration.java
- docs/getting-started/auth.adoc
Detail in https://github.com/aerogear/aerogear-android-sdk/issues/154
Allow custom scopes to be passed in the auth request. Currently this is hardcoded to `openid` by default. We should let the developer decide what scopes they want, and fallback to `openid` if they don't define ones.
> Allow Custom Scopes to be Passed, Allow OAuth

- .circleci/config.yml
- auth/src/test/java/org/aerogear/mobile/auth/UnitTestSuite.java
- auth/src/test/java/org/aerogear/mobile/security/UnitTestSuite.java
- core/src/debug/assets/integration-test-mobile-services.json
- core/src/test/java/org/aerogear/mobile/core/IntegrationTestSuite.java
- core/src/test/java/org/aerogear/mobile/core/UnitTestSuite.java
- core/src/test/java/org/aerogear/mobile/core/integration/MetricsServiceIntegrationTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/MobileCoreTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/configuration/MobileCoreParserTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/configuration/ServiceConfigurationTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/http/OkHttpServiceModuleTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/metrics/MetricsServiceTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/metrics/impl/AppMetricsTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/metrics/impl/DeviceMetricsTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/utils/SanityCheckTest.java
To add integration tests between Android SDK and App Metrics service to our current suite. 
JIRA: https://issues.jboss.org/browse/AEROGEAR-2189
This PR includes a rather major change test-wise:
Two separate test suites have been created: `UnitTestSuite` holds all unit tests and is the one to be run during PRs and local development, whereas `IntegrationTestSuite` holds this integration test and is to be run only in special occasions in Jenkins. In order to run a specific test suite, run:
```
./gradlew :core:testDebug --tests *.IntegrationTestSuite
./gradlew testDebug --tests UnitTestSuite
```
At the moment there aren't any integration tests in `auth`, so that the module has to be filtered as well: `:core:testDebug`.
This commands are only necessary when running from the console, with …
> Add metrics integration test to Android SDK

- .circleci/config.yml
- auth/build.gradle
- build.gradle
- constants.gradle
- core/build.gradle
- example/build.gradle
- gradle/wrapper/gradle-wrapper.properties
While working on push stuff I figure out [Spring dependency management](https://github.com/spring-gradle-plugins/dependency-management-plugin) doesn't work properly with [Gradle transitive dependencies](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html). 
It's ignoring the transitive dependencies and on push, it causes some dependency conflicts. Since Google Services plugin doesn't found any dependency it's going to inject it from your on.
```
Android dependency 'com.google.firebase:firebase-iid' has different version for the compile (11.4.2) and runtime (12.0.1) classpath. 
```
This PR moves all our dependencies version for a [single file](https://github.com/aerogear/aerogear-android-sdk/blob/master/constants.gradle) like most of the libraries do.
Related …
> Replace Spring dependency management by a single gradle file

- example/src/main/assets/mobile-services.json
`clientId` is no longer provided by the Mobile CLI. So we shouldn't have it in our example app either.
Currently we are including the `clientId` in the `mobile-services.json` configuration file for our example app. However, the changes in https://github.com/aerogearcatalog/keycloak-apb/pull/66 means that the `clientId` no longer exists.
This change removes the `clientId` from the example application.
> Remove clientID from mobile-services.json

- example/src/main/assets/mobile-services.json
- push/build.gradle
- push/src/main/java/org/aerogear/mobile/push/MessageHandler.java
- push/src/main/java/org/aerogear/mobile/push/UnifiedPushConfig.java
- push/src/test/java/org/aerogear/mobile/push/UnitTestSuite.java
- push/src/test/java/org/aerogear/mobile/push/unit/UnifiedPushConfigTest.java
Since we are creating a Firebase topic for each category, the categories name needs to follow the [Firebase topic name rules](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging.html#subscribeToTopic(java.lang.String)) 
* [AGDROID-804](https://issues.jboss.org/browse/AGDROID-804)
> Check if push categories follow the Firebase topic name format

- example/src/main/java/org/aerogear/mobile/example/ui/AuthFragment.java
There was an action from the scrum of scrums to add a dialog box on a certificate pinning failure while authenticating in app
- Edit `keycloak` hash value in `mobile-services.json`
- Proceed to Authenticate, request should fail and dialog shown.
> Add warning dialog to example app

- core/src/main/java/org/aerogear/mobile/core/exception/HttpException.java
- core/src/main/java/org/aerogear/mobile/core/http/HttpResponse.java
- core/src/main/java/org/aerogear/mobile/core/http/OkHttpResponse.java
- core/src/test/java/org/aerogear/mobile/core/unit/http/OkHttpServiceModuleTest.java
- push/src/main/java/org/aerogear/mobile/push/PushService.java
While working on https://issues.jboss.org/browse/AEROGEAR-2395 , I noticed the metrics related integration tests pass all the time.
As written in  <https://square.github.io/okhttp/3.x/okhttp/okhttp3/Call.html#execute--> , execute method does not throw an exception when status is 400 or 500. It only throws an exception when there's a connection problem.
But dependent code assumes that `onError` is called when 400 or 500.
To test the wrong behavior, just run the integration tests without the change in the PR. Even when the URL in integration-test-mobile-services.json is something that returns 500, it will pass. Just copy paste metrics service url, but change a letter so that it returns "503 - Service unavailable".
> Make HTTP response calling error callback on 400 or 500

- auth/src/main/java/org/aerogear/mobile/security/SecurityCheckMetricPublisher.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
- auth/src/test/java/org/aerogear/mobile/security/SecurityCheckExecutorTest.java
- core/src/main/java/org/aerogear/mobile/core/metrics/MetricsPublisher.java
- core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
- core/src/main/java/org/aerogear/mobile/core/metrics/impl/DeviceMetrics.java
- core/src/main/java/org/aerogear/mobile/core/metrics/publisher/LoggerMetricsPublisher.java
- core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java
- core/src/test/java/org/aerogear/mobile/core/integration/MetricsServiceIntegrationTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/metrics/MetricsServiceTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/metrics/impl/DeviceMetricsTest.java
- example/src/main/java/org/aerogear/mobile/example/ExampleApplication.java
JIRA: https://issues.jboss.org/browse/AGDROID-801
Depends on https://github.com/aerogear/aerogear-android-sdk/pull/179
2 changes:
- Sends event types ("init" or "security") with metrics
- Security events now contains app and device info
> Security metrics to contain default metrics

- auth/gradle.properties
- core/gradle.properties
the maven artifacts are not named very well:
* `org.aerogear:core` 
* `org.aerogear:auth`
this can mean anything.
Motivation to add some android context on the JARs...
updating the GAV for better names (tm)
> Improving GAV coordinates 

- push/src/main/java/org/aerogear/mobile/push/PushService.java
When the app is killed by the user or device restarts the app will stop to receive background push notifications because it's using [mainThread AppExecutor](https://github.com/aerogear/aerogear-android-sdk/blob/master/core/src/main/java/org/aerogear/mobile/core/executor/AppExecutors.java#L61) instead of [singleThreadService AppExecutor](https://github.com/aerogear/aerogear-android-sdk/blob/master/core/src/main/java/org/aerogear/mobile/core/executor/AppExecutors.java#L69) and `DefaultHandler` will be null because the SDK only retrieve it when `configure` is called.
1. Go to the push screen and register the device on UPS
1. Send a message from UPS with the app in Foreground in the Push screen and you should it theListView
1. Send a message from UPS with the app in Background or in whatever …
> Fix bg push notification

- example/src/main/java/org/aerogear/mobile/example/ui/PushFragment.java
- example/src/main/res/layout/fragment_push.xml
- push/src/main/java/org/aerogear/mobile/push/PushService.java
TL:DR Firebase is calling the [onTokenRefresh()](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService#onTokenRefresh()) on the first time we call [getToken()](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#getToken()) forcing the lib to refresh a token how does not exist yet.
* [AGDROID-808](https://issues.jboss.org/browse/AGDROID-808)
> Avoid to refrehs push token when it does not exists yet

- core/src/main/java/org/aerogear/mobile/core/metrics/publisher/NetworkMetricsPublisher.java
Metrics is now sending the same data twice. 
This is happening due to some copy paste issue that weren't caught on verification.
This PR removes second unneeded call.
> fix: remove unneded post from metrics

- Jenkinsfile
- auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
- auth/src/main/java/org/aerogear/mobile/security/SecurityService.java
- core/src/main/java/org/aerogear/mobile/core/MobileCore.java
- core/src/main/java/org/aerogear/mobile/core/ServiceModule.java
- core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreConfiguration.java
- core/src/main/java/org/aerogear/mobile/core/configuration/MobileCoreJsonParser.java
- core/src/main/java/org/aerogear/mobile/core/configuration/ServiceConfiguration.java
- core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
- core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
- core/src/test/assets/mobile-services-multiple-services-for-type.json
- core/src/test/java/org/aerogear/mobile/core/unit/MobileCoreTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/configuration/MobileCoreParserTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/configuration/ServiceConfigurationTest.java
- example/src/main/java/org/aerogear/mobile/example/ExampleApplication.java
- push/src/main/java/org/aerogear/mobile/push/PushService.java
JIRA: https://issues.jboss.org/browse/AEROGEAR-2669
* After discussion on the mailing list [1] [2], we needed to adapt the SDK in terms of how to get the configs for the services.
* Before, we were using "name" properties for getting the service config. Now we need to use "id" and/or "type" properties.
What's done:
* Introduced methods on MobileCore to
* get config by id --> needed for custom runtime connectors
* get configs by type --> needed when there are multiple configs for a service type
* get config by type --> similar to above, but gets the first one found. this is the one used by mobile core by default for services created automatically (Metrics, Keycloak etc). This is basically the old "getServiceConfiguration" method modified.
* Got rid of the service cache in MobileCore …
> AEROGEAR-2669 - Android SDK should query for configuration type and id

- docs/modules/getting-started/pages/auth-self-defence-checks.adoc
Try to keep docs consistent across the SDKS
Small update to mention the custom self defence checks in the **package offers** section of the security doc.
This was added in the iOS SDK [here](https://github.com/aerogear/aerogear-ios-sdk/pull/111/commits/a018e256ed6eb734ce781cf43f577fecf728e5cc)
> mention custom security checks in package offers section

- Jenkinsfile
Integration test in Jenkins was hanging because of incorrect name of the node label
> Fixed node label in Jenkinsfile

- README.md
- docs/modules/ROOT/pages/push.adoc
Fix the paths to the docs in the README (looks like they changed with Antora). Also updates the example code to register a device for push.
> fix paths to docs

- constants.gradle
- docs/modules/ROOT/pages/using-push-sdk.adoc
- push/build.gradle
- push/src/main/java/org/aerogear/mobile/push/PushService.java
- push/src/main/java/org/aerogear/mobile/push/UnifiedPushCredentials.java
- push/src/main/java/org/aerogear/mobile/push/fcm/AeroGearFirebaseInstanceIdService.java
This is part of the [AGDROID-796](https://issues.jboss.org/browse/AGDROID-796)
Credentials provided by _mobile-services.json_
```
{
"version": 1,
"clusterName": "https://someURL",
"namespace": "myNamespace
"clientId": "myClienId",
"services": [
{
"id": "myPushId",
"name": "push",
"url": "https://someURL/",
"type": "push",
"config": {
"android": {
"variantId": "[variant id]",
"variantSecret": "[variant secret]",
"senderId": "[firebase project number]"
}
}
}
]
}
```
Replace:
```java
PushService pushService = MobileCore.getInstance().getService(PushService.class);
```
By
```java
PushService pushService = new PushService.Builder().openshift().build();
```
> Decouple Push Service creation from MobileCore

- core/src/main/java/org/aerogear/mobile/core/metrics/MetricsService.java
https://issues.jboss.org/browse/AEROGEAR-3079
Metrics service returns 204 instead of 200 when publishing new metrics data.
> AEROGEAR-3079 Fix metrics response handling

- security/src/main/java/org/aerogear/mobile/security/SecurityCheckMetricPublisher.java
- security/src/test/java/org/aerogear/mobile/security/SecurityCheckExecutorTest.java
The showcase app wasn't sending metrics for device checks.  This is now fixed
JIRA: https://issues.jboss.org/browse/AEROGEAR-3130
The metrics published was not attaching a responder to a request object.  Rx objects don't run unless they have a response to send things to.  There may be a need to update some javadocs to clarify this at the metricsPublisher level; this is documented behavior on the Request class as well as a standard Rx pattern (cold single observable) which is documented on the request class as well.
To verify this issue you can use the showcase app, you will need to provision metrics and make sure that you either import the https certificate or use an insecure route.
> Security metrics are now sent

- auth/src/test/java/org/aerogear/mobile/auth/AuthServiceTest.java
- auth/src/test/java/org/aerogear/mobile/auth/credentials/JwksManagerTest.java
- core/src/main/java/org/aerogear/mobile/core/MobileCore.java
- core/src/main/java/org/aerogear/mobile/core/http/HttpRequest.java
- core/src/main/java/org/aerogear/mobile/core/http/HttpResponse.java
- core/src/main/java/org/aerogear/mobile/core/http/OkHttpServiceModule.java
Small refactor to expose OKHttp as our defactor http implementation.  I left the interfaces in for testing and backwards compatibility, but we can discuss removing them.
https://issues.jboss.org/browse/AEROGEAR-7542
This makes a few small changes.
MobileCore getHttpLayer returns a OkHttpService.  
OKHttpService now has a method to get the http client as well as javadocs covering how it is configured.
Contact @danielpassos for additional testing information.
> Exposing http client

- codequality/lint/gradle/wrapper/gradle-wrapper.properties
`./gradlew checks:jar` command does not work with 4.1. And besides Gradle 4.6 is used everywhere else.
> Updated Gradle for lint to 4.6

- CONTRIBUTING.md
- core/src/test/assets/mobile-services-multiple-services-for-type.json
- core/src/test/assets/mobile-services-type-casing.json
- core/src/test/assets/mobile-services.json
- core/src/test/java/org/aerogear/mobile/core/integration/MetricsServiceIntegrationTest.java
- core/src/test/java/org/aerogear/mobile/core/unit/metrics/MetricsServiceTest.java
Metrics Integration test keeps failing and the metrics endpoint is not configurable as described.
Issue: https://github.com/aerogear/aerogear-android-sdk/issues/265
Hard-coded metrics URL in the integration test has been removed. It has been made configurable via mobile-services.json file. Already existing classes for parsing and getting the configuration have been used for that.
Some other small fixes are included that are related to this - not using the mockable.io URL at all. If the URL does not matter, that fact has been made clear by changing the URL to contain word 'dummy'.
We have to remove this note that is automatically prefilled in description of PR because it is not that easy to run the integration test now:
```
NOTE 
To run the integration tests, select "test/integration" …
```
> Fixing URL for app metrics integration test

- .circleci/config.yml
Having https://github.com/aerogear/aerogear-android-sdk/pull/270 merged it is OK to run `test` task since this task only triggers unit test execution. And we definitely don't want to upload archives if the unit tests are failing.
This is basically a revert of https://github.com/aerogear/aerogear-android-sdk/commit/c67c0503a5d75ba754ef1475f84c42c69e2ad49b which is not needed any longer I think
> Execute unit tests before publishing

- Jenkinsfile
Fix of the command that triggers integration test execution. It has changed, see https://github.com/aerogear/aerogear-android-sdk/pull/270
> Fixed command for integration tests execution

- CONTRIBUTING.md
- auth/build.gradle
- build.gradle
- core/build.gradle
- jacoco.gradle
- push/build.gradle
- security/build.gradle
Having code coverage computed is very useful.
Added some JaCoCo config and tasks that are able to generate the code coverage reports - for each module individually (jacoco.gradle) and for 'root' report that combines all the module reports together (build.gradle). The build. gradle also contains few variables used in both individual and root jacoco tasks to avoid duplicity definitions of these variables.
Next step would be to integrate with coverals or codecov and add nice badge to README.md so that we can track the trend of code coverage over the time.
> Added Code Coverage

- auth/build.gradle
Hardcoded scheme in gradle file is no longer applied and it should be removed. 
Users should specify their own version.
I'm not 100% sure about that change, but IMHO users will need to specify that in their application rather than in SDK. SDK requires schema to be passed in so this looks like value that will be never used, however in recent version of SDK I'm getting back compilation issues.
> Remove hardcoded scheme from example

- build.gradle
- jacoco.gradle
- sync/build.gradle
After recent addition of sync module the jacoco report generation must be fixed
jacoco.gradle applied for sync. This way all the modules (auth, core, push, security, sync) has `jacocoTestReport` task.
Updated `jacocoRootReport` task so as not to fail if there are data missing. Data are missing for sync because there are no unit tests implemented.
Task `createDebugCoverageReport` has been removed due to #278. This is due to this task being dependent on `processDebugAndroidTestManifest` and this task no longer work for auth module. It has no effect on code coverage generated.
Once this is merged, I will proceed with https://github.com/aerogear/aerogear-android-sdk/pull/284 where currently the checks failed.
> Fixed JaCoCo report after sync module addition

- auth/src/main/java/org/aerogear/mobile/auth/AuthHeaderProvider.java
- auth/src/main/java/org/aerogear/mobile/auth/AuthService.java
Both `getFreshUser` and `getCurrentUser` returns the current logged in user. The difference is that the `getFreshUser` automatically refresh the token if needed.
Instead of duplicating code, this PR changes it to a parameter.
Moreover, this PR make android code coherent with what we have in the other platforms (iOS and Xamarin)
> Renamed getFreshUser to getCurrentUser(boolean autorefresh)
